### ISSUE TITLE
Add support for pomless integration testing

### ISSUE THREAD

**Issue by mariuszs** [takari/takari-plugin-testing-project#10]
Currently pomless test fails
```
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/mariuszs/git/props2yaml/maven-plugin/target/test-projects/IntegrationTest_testBasic[3.3.3]_pomless). Please verify you invoked Maven from the correct directory. -> [Help 1]
org.apache.maven.lifecycle.MissingProjectException: The goal you specified requires a project to execute but there is no POM in this directory (/home/mariuszs/git/props2yaml/maven-plugin/target/test-projects/IntegrationTest_testBasic[3.3.3]_pomless). Please verify you invoked Maven from the correct directory.
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:84)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.takari.maven.testing.executor.Embedded3xLauncher.run(Embedded3xLauncher.java:360)
	at io.takari.maven.testing.executor.MavenExecution.execute(MavenExecution.java:51)
	at io.codearte.props2yaml.maven.IntegrationTest.testBasic(IntegrationTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
[ERROR] 
```

**Comment by ifedorenko** [comment]
Integration tests harness just runs Maven. If the goal you try to execute requires a project, as the error message appears to suggest, then the test will fail without valid pom.xml. If you believe this is not the case, please provide a small standalone example that runs from command line using `mvn` but fails when run through the test harness.

**Comment by mariuszs** [comment]
Sampple minimal project: https://github.com/mariuszs/maven-pomless-plugin

**Comment by mariuszs** [comment]
Sample build:

https://travis-ci.org/mariuszs/maven-pomless-plugin/builds/87442926

**Comment by ifedorenko** [comment]
I get exactly the same error running `mvn pomless` on command line as during the integration test

```
mpb:tmp igor$ mvn pomless
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.266 s
[INFO] Finished at: 2015-10-26T09:56:51-04:00
[INFO] Final Memory: 7M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/private/tmp). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
```

**Comment by mariuszs** [comment]
Maybe different maven version, please check logs:

https://travis-ci.org/mariuszs/maven-pomless-plugin/builds/87551647#L1189

```
mvn --version                                                                                                                          
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /home/mariuszs/sdk/maven
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_60/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.2.3-300.fc23.x86_64", arch: "amd64", family: "unix"
```

**Comment by mariuszs** [comment]
Ok, my test is using wrong goal. Is this any way to make this working?

**Comment by ifedorenko** [comment]
You need specify fully-qualifier goal name, both on command line and during integration test, i.e. `io.codearte.maven:maven-pomless-plugin:1.0-SNAPSHOT:pomless`. Of course, don't use literal `1.0-SNAPSHOT` in the test, but use `project.version` test property value.

**Comment by mariuszs** [comment]
Thanks!

**Comment by mariuszs** [comment]
@ifedorenko How to read this `project.version` inside IntegationTest class?

**Comment by mariuszs** [comment]
I have found: ```testProperties.getPluginVersion()```
